# Dependabot will run on day 16 of each month at 01:14 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "14 1 16 * *"
    open-pull-requests-limit: 20
    assignees:
      - "BenAhrdt"
    versioning-strategy: "increase"
